version: '3'
volumes:
  prometheus_data: {}
  grafana_data: {}
  
services:
  consul_agent_1: &consul_agent
    image: consul:1.6.1
    command: "agent -retry-join ${CONSUL_CLUSTER}_consul_server_bootstrap_1 -client 0.0.0.0"
    volumes:
        - ./consul/config:/consul/config
        
  consul_agent_2:
    <<: *consul_agent

  consul_agent_3:
    <<: *consul_agent

  consul_server_1: &consul_server
    <<: *consul_agent
    command: "agent -server -retry-join ${CONSUL_CLUSTER}_consul_server_bootstrap_1 -client 0.0.0.0"
    volumes:
        - ./consul/config:/consul/config
        - ./consul/data/consul01:/consul/data

  consul_server_2:
    <<: *consul_server
    volumes:
        - ./consul/config:/consul/config
        - ./consul/data/consul02:/consul/data

  consul_server_bootstrap:
    <<: *consul_agent
    image: consul:1.6.1
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    volumes:
        - ./consul/config:/consul/config
        - ./consul/data/consul03:/consul/data

## VAULT cluster configuration
  pki: &pki
    image: vault-prem:1.2.3
    volumes:
      - ./pki/ca:/vault/ca
      - ./pki/config:/vault/config
      - ./pki/logs/:/vault/logs
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
      - VAULT_LOG_LEVEL=debug
    command: vault server -config=/vault/config/vault-pki.hcl
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul_agent_1
  vault01: &vault_server
    image: vault-prem:1.2.3
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs/vault01:/vault/logs
    environment:
      #- VAULT_CLUSTER_INTERFACE=eth0
      - VAULT_REDIRECT_INTERFACE=eth0
      #- VAULT_API_ADDR=http://vault01:8200
      - VAULT_LOG_LEVEL=debug
    command: vault server -config=/vault/config/vault01.hcl
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul_agent_1
  
  vault02:
    <<: *vault_server
    volumes:
      - ./vault/config:/vault/config/
      - ./vault/logs/vault02:/vault/logs
    depends_on:
      - consul_agent_2
    command: vault server -config=/vault/config/vault02.hcl
      
  vault03:
    <<: *vault_server
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs/vault02:/vault/logs
    depends_on:
      - consul_agent_3   
    command: vault server -config=/vault/config/vault03.hcl 
## Prometheus Stack
## Based on https://github.com/vegasbrianc/prometheus
  prometheus: &prometheus
    image: prom/prometheus:v2.14.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--log.level=debug'
    # ports:
    #   - 9090:9090
    restart: always
  
  # cadvisor: &cadvisor
  #   image: gcr.io/google-containers/cadvisor:v0.34.0
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   # ports:
  #   #   - 8080:8080
  #   restart: always

  grafana: &grafana
    image: grafana/grafana:6.5.2
    user: "104"
    depends_on:
       - prometheus
    # ports:
    #   - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always