version: '3'

services:
  consul_agent_1: &consul_agent
    image: consul:1.6.1
    command: "agent -retry-join ${CONSUL_CLUSTER}_consul_server_bootstrap_1 -client 0.0.0.0"
    volumes:
        - ./consul/config:/consul/config
        
  consul_agent_2:
    <<: *consul_agent

  consul_agent_3:
    <<: *consul_agent

  consul_server_1: &consul_server
    <<: *consul_agent
    command: "agent -server -retry-join ${CONSUL_CLUSTER}_consul_server_bootstrap_1 -client 0.0.0.0"
    volumes:
        - ./consul/config:/consul/config
        - ./consul/data/consul01:/consul/data

  consul_server_2:
    <<: *consul_server
    volumes:
        - ./consul/config:/consul/config
        - ./consul/data/consul02:/consul/data

  consul_server_bootstrap:
    <<: *consul_agent
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    volumes:
        - ./consul/config:/consul/config
        - ./consul/data/consul03:/consul/data

## VAULT cluster configuration
  vault01: &vault_server
    image: vault-prem:1.2.3
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs/vault01:/vault/logs
    environment:
      #- VAULT_CLUSTER_INTERFACE=eth0
      - VAULT_REDIRECT_INTERFACE=eth0
      #- VAULT_API_ADDR=http://vault01:8200
      - VAULT_LOG_LEVEL=debug
    command: vault server -config=/vault/config/vault01.hcl
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul_agent_1
  
  vault02:
    <<: *vault_server
    volumes:
      - ./vault/config:/vault/config/
      - ./vault/logs/vault02:/vault/logs
    depends_on:
      - consul_agent_2
    command: vault server -config=/vault/config/vault02.hcl
      
  vault03:
    <<: *vault_server
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs/vault02:/vault/logs
    depends_on:
      - consul_agent_3   
    command: vault server -config=/vault/config/vault03.hcl 
