version: '3'
networks:
  vault_secondary:
    external: true

services:
  consul_agent_1: &consul-agent
    networks:
      - vault_secondary
  
  consul_agent_2:
    networks:
      - vault_secondary

  consul_agent_3:
    networks:
      - vault_secondary

  consul_server_1: &consul_server
    networks:
      - vault_secondary

  consul_server_2:
    networks:
      - vault_secondary

  consul_server_bootstrap:
    networks:
      - vault_secondary
    ports:
      - "8402:8400"
      - "8502:8500"
      - "8602:8600"
      - "8602:8600/udp"

## VAULT cluster configuration
  vault01: &vault-server
    networks:
      - vault_secondary    
    ports:
      - 9301:8200
  
  vault02: 
    networks:
      - vault_secondary  
    ports:
      - 9302:8200
      
  vault03:
    networks:
      - vault_secondary  
    ports:
      - 9303:8200
