---
test_name: 01-Create secondary-token
stages:
  - name: 01-Create secondary-token
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/replication/performance/primary/secondary-token"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"      
      json:
        id: "secondary"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            mydir: "{tavern.env_vars.VAULT_CLUSTER}"
            filename: secondary-token.json
