---
test_name: 01-Init Vault
stages:
  - name: 01-Init Vault
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/sys/init"
      method: PUT
      json:
        secret_shares: 1
        secret_threshold: 1
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            mydir: "{tavern.env_vars.VAULT_CLUSTER}"
            filename: init.json
        body:
          keys: keys
          root_token: root_token
