---
test_name: 01-Create vault server certificate
stages:

  - name: 02-Create vault01 server certificate
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/issue/dc1-vault"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        common_name: "vault01.dc1.vault"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filename: vault01-dc1-vault.json
  - name: 03-Create vault02 server certificate
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/issue/dc1-vault"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        common_name: "vault02.dc1.vault"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filename: vault02-dc1-vault.json
  - name: 04-Create vault03 server certificate
    request:
      url: "{tavern.env_vars.VAULT_ADDR}/v1/pki/issue/dc1-vault"
      method: POST
      headers:
        X-Vault-Token: "{tavern.env_vars.VAULT_TOKEN}"
      json:
        common_name: "vault03.dc1.vault"
        ttl": "720h"
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            filename: vault03-dc1-vault.json
