---
test_name: 01-Unseal Vault
stages:
  - name: 01-Unseal Vault
    request:
      url: "{env_vars.VAULT_ADDR}/v1/sys/unseal"
      method: PUT
      json:
        key: "{ext.keys_0}"
        $ext:
          function: extensions.read_json
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/init.json"
            sub_vars: True
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "{env_vars.VAULT_DATA}/unsealed_response.json"
