---
stages:
  - name: 01-Unseal Vault
    request:
      url: "{env_vars.VAULT_ADDR}"
      method: PUT
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"      
      json:
        keys: "{ext.keys_0}"
        key2: val2
        $ext:
          function: extensions.read_json
          extra_kwargs:
            path: "data/{env_vars.VAULT_CLUSTER}/init.json"
            sub_vars: True
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            path: "data/{env_vars.VAULT_CLUSTER}/unsealed_response.json"
