---
stages:
  - name: 01-Unseal Vault
    request:
      url: "{env_vars.VAULT_ADDR}/v1/sys/unseal"
      method: PUT
      json:
        $ext:
          function: myutils:read_init
          extra_kwargs:
            mydir: "{env_vars.VAULT_CLUSTER}"
            filename: init.json
    response:
      status_code: 200
      save:
        $ext:
          function: myutils:save_response
          extra_kwargs:
            mydir: "{env_vars.VAULT_CLUSTER}"
            filename: unsealed_response.json
