---
stages:
  - name: 01-Unseal Vault
    request:
      url: "{env_vars.VAULT_ADDR}"
      method: PUT
      headers:
        X-Vault-Token: "{env_vars.VAULT_TOKEN}"      
      json:
        key1: val1
        key2: val2
        $ext:
          function: extensions.read_file
          extra_kwargs:
            mydir: "{env_vars.VAULT_CLUSTER}"
            filename: init.json
    response:
      status_code: 200
      save:
        $ext:
          function: extensions.save_response
          extra_kwargs:
            mydir: "{env_vars.VAULT_CLUSTER}"
            filename: unsealed_response.json
